R CMD INSTALL  Rcpp_0.12.1.tar.gz
R CMD INSTALL  Matrix_1.2-2.tar.gz
R CMD INSTALL  RcppEigen_0.3.2.5.0.tar.gz
R CMD INSTALL  minqa_1.2.4.tar.gz
R CMD INSTALL  nloptr_1.0.4.tar.gz
R CMD INSTALL  lme4_1.1-9.tar.gz
R CMD INSTALL  e1071_1.6-7.tar.gz
R CMD INSTALL  TeachingDemos_2.9.tar.gz
R CMD INSTALL  plotrix_3.5-12.tar.gz
R CMD INSTALL  plotmo_3.1.4.tar.gz
R CMD INSTALL  earth_4.4.2.tar.gz
R CMD INSTALL  fastICA_1.2-0.tar.gz
R CMD INSTALL  iterators_1.0.7.tar.gz
R CMD INSTALL  foreach_1.4.2.tar.gz
R CMD INSTALL  gam_1.12.tar.gz
R CMD INSTALL  numDeriv_2014.2-1.tar.gz
R CMD INSTALL  lava_1.4.1.tar.gz
R CMD INSTALL  prodlim_1.5.1.tar.gz
R CMD INSTALL  rpart_4.1-10.tar.gz
R CMD INSTALL  ipred_0.9-5.tar.gz
R CMD INSTALL  kernlab_0.9-22.tar.gz
R CMD INSTALL  combinat_0.0-8.tar.gz
R CMD INSTALL  klaR_0.6-12.tar.gz
R CMD INSTALL  ellipse_0.3-8.tar.gz
R CMD INSTALL  mda_0.4-7.tar.gz
R CMD INSTALL  mlbench_2.1-1.tar.gz
R CMD INSTALL  lattice_0.20-33.tar.gz
R CMD INSTALL  zoo_1.7-12.tar.gz
R CMD INSTALL  sandwich_2.3-3.tar.gz
R CMD INSTALL  strucchange_1.5-1.tar.gz
R CMD INSTALL  modeltools_0.2-21.tar.gz
R CMD INSTALL  mvtnorm_1.0-3.tar.gz
R CMD INSTALL  coin_1.0-24.tar.gz
R CMD INSTALL  party_1.0-18.tar.gz
R CMD INSTALL  partykit_1.0-3.tar.gz
R CMD INSTALL  pls_2.4-3.tar.gz
R CMD INSTALL  plyr_1.8.3.tar.gz
R CMD INSTALL  pROC_1.8.tar.gz
R CMD INSTALL  proxy_0.4-15.tar.gz
R CMD INSTALL  randomForest_4.6-10.tar.gz
R CMD INSTALL  RANN_2.5.tar.gz
R CMD INSTALL  spls_2.2-1.tar.gz
R CMD INSTALL  subselect_0.12-5.tar.gz
R CMD INSTALL  pamr_1.55.tar.gz
R CMD INSTALL  superpc_1.09.tar.gz
R CMD INSTALL  stringi_0.5-5.tar.gz
R CMD INSTALL  magrittr_1.5.tar.gz
R CMD INSTALL  stringr_1.0.0.tar.gz
R CMD INSTALL  reshape2_1.4.1.tar.gz
R CMD INSTALL  Cubist_0.0.18.tar.gz
R CMD INSTALL  digest_0.6.8.tar.gz
R CMD INSTALL  memoise_0.2.1.tar.gz
R CMD INSTALL  crayon_1.3.1.tar.gz
R CMD INSTALL  testthat_0.10.0.tar.gz
R CMD INSTALL  pbkrtest_0.4-2.tar.gz
R CMD INSTALL  SparseM_1.7.tar.gz
R CMD INSTALL  MatrixModels_0.4-1.tar.gz
R CMD INSTALL  quantreg_5.19.tar.gz
R CMD INSTALL  car_2.0-25.tar.gz
R CMD INSTALL  ISwR_2.0-7.tar.gz
R CMD INSTALL  iterators_1.0.7.tar.gz
R CMD INSTALL  nlme_3.1-122.tar.gz
R CMD INSTALL  profileModel_0.5-9.tar.gz
R CMD INSTALL  brglm_0.5-9.tar.gz
R CMD INSTALL  gtools_3.5.0.tar.gz
R CMD INSTALL  BradleyTerry2_1.0-6.tar.gz
R CMD INSTALL  gtable_0.1.2.tar.gz
R CMD INSTALL  RColorBrewer_1.1-2.tar.gz
R CMD INSTALL  dichromat_2.0-0.tar.gz
R CMD INSTALL  colorspace_1.2-6.tar.gz
R CMD INSTALL  munsell_0.4.2.tar.gz
R CMD INSTALL  labeling_0.3.tar.gz
R CMD INSTALL  scales_0.3.0.tar.gz
R CMD INSTALL  BiocGenerics_0.8.0.tar.gz
R CMD INSTALL  graph_1.40.1.tar.gz
R CMD INSTALL  Rgraphviz_2.6.0.tar.gz
R CMD INSTALL  proto_0.3-10.tar.gz
R CMD INSTALL  ggplot2_1.0.1.tar.gz
R CMD INSTALL  caret_6.0-52.tar.gz
R CMD INSTALL  abind_1.4-3.tar.gz
R CMD INSTALL  acepack_1.3-3.3.tar.gz
R CMD INSTALL  ada_2.0-3.tar.gz
R CMD INSTALL  adabag_4.0.tar.gz
R CMD INSTALL  lmtest_0.9-34.tar.gz
R CMD INSTALL  Formula_1.2-1.tar.gz
R CMD INSTALL  AER_1.2-4.tar.gz
R CMD INSTALL  zlibbioc_1.8.0.tar.gz
R CMD INSTALL  affyio_1.30.0.tar.gz
R CMD INSTALL  preprocessCore_1.24.0.tar.gz
R CMD INSTALL  Biobase_2.22.0.tar.gz
R CMD INSTALL  BiocInstaller_1.12.1.tar.gz
R CMD INSTALL  affy_1.40.0.tar.gz
R CMD INSTALL  gamlss.data_4.3-0.tar.gz
R CMD INSTALL  gamlss.dist_4.3-5.tar.gz
R CMD INSTALL  gamlss_4.3-6.tar.gz
R CMD INSTALL  AGD_0.35.tar.gz
R CMD INSTALL  akima_0.5-11.tar.gz
R CMD INSTALL  animation_2.3.tar.gz
R CMD INSTALL  DBI_0.3.1.tar.gz
R CMD INSTALL  RSQLite_1.0.0.tar.gz
R CMD INSTALL  IRanges_1.20.7.tar.gz
R CMD INSTALL  AnnotationDbi_1.24.0.tar.gz
R CMD INSTALL  ape_3.3.tar.gz
R CMD INSTALL  bdsmatrix_1.3-2.tar.gz
R CMD INSTALL  biglm_0.9-1.tar.gz
R CMD INSTALL  bitops_1.0-6.tar.gz
R CMD INSTALL  rFerns_1.1.0.tar.gz
R CMD INSTALL  Boruta_4.0.0.tar.gz
R CMD INSTALL  gbm_2.1.1.tar.gz
R CMD INSTALL  bst_0.3-4.tar.gz
R CMD INSTALL  C50_0.1.0-24.tar.gz
R CMD INSTALL  ca_0.58.tar.gz
R CMD INSTALL  heplots_1.0-16.tar.gz
R CMD INSTALL  candisc_0.6-7.tar.gz
R CMD INSTALL  catdata_1.2.1.tar.gz
R CMD INSTALL  cba_0.2-15.tar.gz
R CMD INSTALL  chron_2.3-47.tar.gz
R CMD INSTALL  clue_0.3-50.tar.gz
R CMD INSTALL  coda_0.17-1.tar.gz
R CMD INSTALL  CompQuadForm_1.4.1.tar.gz
R CMD INSTALL  corpcor_1.6.8.tar.gz
R CMD INSTALL  corrplot_0.73.tar.gz
R CMD INSTALL  coxme_2.2-5.tar.gz
R CMD INSTALL  date_1.2-34.tar.gz
R CMD INSTALL  deldir_0.1-9.tar.gz
R CMD INSTALL  manipulate_1.0.1.tar.gz
R CMD INSTALL  BH_1.58.0-1.tar.gz
R CMD INSTALL  DescTools_0.99.13.tar.gz
R CMD INSTALL  diptest_0.75-7.tar.gz
R CMD INSTALL  doMC_1.3.3.tar.gz
R CMD INSTALL  snow_0.3-13.tar.gz
R CMD INSTALL  doSNOW_1.0.12.tar.gz
R CMD INSTALL  som_0.3-5.tar.gz
R CMD INSTALL  sp_1.2-0.tar.gz
R CMD INSTALL  spam_1.0-1.tar.gz
R CMD INSTALL tensor_1.5.tar.gz
R CMD INSTALL polyclip_1.3-2.tar.gz
R CMD INSTALL goftest_1.0-3.tar.gz
R CMD INSTALL  spatstat_1.40-0.tar.gz 
R CMD INSTALL  stabs_0.5-1.tar.gz
R CMD INSTALL  dynlm_0.3-3.tar.gz
R CMD INSTALL  effects_3.0-4.tar.gz
R CMD INSTALL  expm_0.99-1.1.tar.gz
R CMD INSTALL  Fahrmeir_2015.6.25.tar.gz
R CMD INSTALL  fit.models_0.5-10.tar.gz
R CMD INSTALL  forward_1.0.3.tar.gz
R CMD INSTALL  GAMBoost_1.2-3.tar.gz
R CMD INSTALL  gclus_1.3.1.tar.gz
R CMD INSTALL  gee_4.13-19.tar.gz
R CMD INSTALL  geepack_1.2-0.tar.gz
R CMD INSTALL  glmmML_1.0.tar.gz
R CMD INSTALL  glmnet_2.0-2.tar.gz
R CMD INSTALL  qvcalc_0.8-9.tar.gz
R CMD INSTALL  relimp_1.0-4.tar.gz
R CMD INSTALL  gnm_1.0-8.tar.gz
R CMD INSTALL  GPArotation_2014.11-1.tar.gz
R CMD INSTALL  gpclib_1.5-5.tar.gz
R CMD INSTALL  gridBase_0.4-7.tar.gz
R CMD INSTALL  hexbin_1.27.0.tar.gz
R CMD INSTALL  highlight_0.4.7.tar.gz
R CMD INSTALL  latticeExtra_0.6-26.tar.gz
R CMD INSTALL  gridExtra_2.0.0.tar.gz
R CMD INSTALL  Hmisc_3.16-0.tar.gz
R CMD INSTALL  HSAUR_1.3-7.tar.gz
R CMD INSTALL  registry_0.3.tar.gz 
R CMD INSTALL  xtable_1.7-4.tar.gz
R CMD INSTALL  pkgmaker_0.22.tar.gz
R CMD INSTALL  rngtools_1.2.4.tar.gz
R CMD INSTALL  doParallel_1.0.8.tar.gz
R CMD INSTALL  NMF_0.20.6.tar.gz
R CMD INSTALL  irlba_1.0.3.tar.gz
R CMD INSTALL  igraph_1.0.1.tar.gz
R CMD INSTALL  igraphdata_1.0.1.tar.gz
R CMD INSTALL  ineq_0.2-13.tar.gz
R CMD INSTALL  inline_0.3.14.tar.gz
R CMD INSTALL  isa2_0.3.4.tar.gz
R CMD INSTALL  quadprog_1.5-5.tar.gz
R CMD INSTALL  kinship2_1.6.4.tar.gz
R CMD INSTALL  lars_1.2.tar.gz
R CMD INSTALL  leaps_2.9.tar.gz
R CMD INSTALL  limma_3.18.13.tar.gz
R CMD INSTALL  locfit_1.5-9.1.tar.gz
R CMD INSTALL  logspline_2.1.8.tar.gz
R CMD INSTALL  lpSolve_5.6.12.tar.gz
R CMD INSTALL  lqa_1.0-3.tar.gz
R CMD INSTALL  maps_2.3-11.tar.gz
R CMD INSTALL  mapproj_1.2-4.tar.gz
R CMD INSTALL  maptools_0.8-36.tar.gz
R CMD INSTALL  marray_1.40.0.tar.gz
R CMD INSTALL  Matching_4.8-3.4.tar.gz
R CMD INSTALL  MatchIt_2.4-21.tar.gz
R CMD INSTALL  miscTools_0.6-16.tar.gz
R CMD INSTALL  maxLik_1.2-4.tar.gz
R CMD INSTALL  MBESS_3.3.3.tar.gz
R CMD INSTALL  mclust_5.0.2.tar.gz
R CMD INSTALL  MCMCpack_1.3-3.tar.gz
R CMD INSTALL  mice_2.22.tar.gz
R CMD INSTALL  microbenchmark_1.4-2.tar.gz
R CMD INSTALL  misc3d_0.8-4.tar.gz
R CMD INSTALL  mitools_2.3.tar.gz
R CMD INSTALL  mix_1.0-9.tar.gz
R CMD INSTALL  mnormt_1.5-3.tar.gz
R CMD INSTALL  mondate_0.10.01.02.tar.gz
R CMD INSTALL  MPV_1.38.tar.gz
R CMD INSTALL  TH.data_1.0-6.tar.gz
R CMD INSTALL  multcomp_1.4-1.tar.gz
R CMD INSTALL  multicool_0.1-7.tar.gz
R CMD INSTALL  multtest_2.18.0.tar.gz
R CMD INSTALL  MuMIn_1.15.1.tar.gz
R CMD INSTALL  mvnormtest_0.1-9.tar.gz
R CMD INSTALL  nor1mix_1.2-1.tar.gz
R CMD INSTALL  nws_1.7.0.1.tar.gz
R CMD INSTALL  oz_1.0-20.tar.gz
R CMD INSTALL  pan_1.3.tar.gz
R CMD INSTALL  PBSmapping_2.69.76.tar.gz
R CMD INSTALL  pcaPP_1.9-60.tar.gz
R CMD INSTALL  penalized_0.9-45.tar.gz
R CMD INSTALL  pkgKitten_0.1.3.tar.gz
R CMD INSTALL  PKPDmodels_0.3.2.tar.gz
R CMD INSTALL  plm_1.4-0.tar.gz
R CMD INSTALL  png_0.1-7.tar.gz
R CMD INSTALL  scatterplot3d_0.3-36.tar.gz
R CMD INSTALL  poLCA_1.4.1.tar.gz
R CMD INSTALL  polspline_1.1.12.tar.gz
R CMD INSTALL  sfsmisc_1.0-28.tar.gz
R CMD INSTALL  polycor_0.7-8.tar.gz
R CMD INSTALL  polynom_1.3-8.tar.gz
R CMD INSTALL  prefmod_0.8-32.tar.gz
R CMD INSTALL  pscl_1.4.9.tar.gz
R CMD INSTALL  quantreg_5.19.tar.gz
R CMD INSTALL  rbenchmark_1.0.0.tar.gz
R CMD INSTALL  Rcompression_0.93-2.tar.gz
R CMD INSTALL  rgenoud_5.7-12.4.tar.gz
R CMD INSTALL  rhdf5_2.6.0.tar.gz
R CMD INSTALL  rlecuyer_0.3-3.tar.gz
R CMD INSTALL  rmeta_2.16.tar.gz
R CMD INSTALL  survival_2.38-3.tar.gz
R CMD INSTALL  rms_4.3-1.tar.gz
R CMD INSTALL  RSVGTipsDevice_1.0-4.tar.gz
R CMD INSTALL  Rsymphony_0.1-21.tar.gz  ## for installation of rsymphoney sudo apt-get install coinor-libcgl-dev coinor-libsymphony-dev cdbs coinor-libcgl-dev 
R CMD INSTALL  RUnit_0.4.29.tar.gz
R CMD INSTALL  systemfit_1.1-18.tar.gz
R CMD INSTALL  sampleSelection_1.0-2.tar.gz
R CMD INSTALL  shapefiles_0.7.tar.gz
R CMD INSTALL  slam_0.1-32.tar.gz
R CMD INSTALL  Sleuth2_1.0-7.tar.gz
R CMD INSTALL  SuppDists_1.1-9.1.tar.gz
R CMD INSTALL  survey_3.30-3.tar.gz
R CMD INSTALL  tables_0.7.79.tar.gz
R CMD INSTALL  testit_0.4.tar.gz
R CMD INSTALL  timeDate_3012.100.tar.gz
R CMD INSTALL  tis_1.30.tar.gz
R CMD INSTALL  tripack_1.3-6.tar.gz
R CMD INSTALL  truncreg_0.2-1.tar.gz
R CMD INSTALL  tseries_0.10-34.tar.gz
R CMD INSTALL  TSA_1.01.tar.gz
R CMD INSTALL  urca_1.2-8.tar.gz
R CMD INSTALL  vcd_1.4-1.tar.gz
R CMD INSTALL  VGAM_0.9-8.tar.gz
R CMD INSTALL  VGAMdata_0.9-7.tar.gz
R CMD INSTALL  Zelig_4.2-1.tar.gz
R CMD INSTALL  Rmpi_0.6-5.tar.gz ## sudo apt-get install libopenmpi-dev
